### ISSUE TITLE
Misspelling in file name descriptions

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/breadcrumb_learn#9] opened 2021-09-15 15:55 UTC
1.jpg
Added tower assmebly
yesterday
angle_parts.jpg
Added tower assmebly
yesterday
angle_parts.png
Added tower assmebly

**Comment by JanezCim** [comment] 2021-09-16 07:35
Duplicate of #10

**Closed by JanezCim** 2021-09-16 07:35 UTC
